# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78e6fefbccf2a08aeb40ae77a81ae013d635c2f0a67833b967e9723a8af3b8281d6644386e265c5013cbd2d94c8c86be8767e1a92d3962ef63dc2075e5e8c37

test:
  secret_key_base: 9d948deb4c84d4ebc273c70009b6ba16e0e7fc906f07b41577ab8c625fc03f3b73fbd63ce69dcff5398e755bfa188edd83143ca619c20b20a9292c2e65bd706f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
