dino1 = Dinosaur.create( { name: "Iguanodon", age: 3, image_url: "https://goo.gl/wB6q9q" } )
dino2 = Dinosaur.create( { name: "Mosasaurus", age: 10, image_url: "https://goo.gl/aoZsYt" } )
dino3 = Dinosaur.create( { name: "Hungarosaurus", age: 15, image_url: "https://goo.gl/EqRlgP" } )
dino4 = Dinosaur.create( { name: "Thyreophora", age: 8, image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTC5gSjaaOG0fKxN-E_j-LwLNwjk992y81_qZxNb29ZuO6lVTX-Zw" } )
dino5 = Dinosaur.create( { name: "Theropoda", age: 5, image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlMJ9_ErTDPKSOv6h3lGrlp539jw0G5rM7_eiJOld8C-NQn5Am" } )
